/* eslint-disable react/no-unescaped-entities */
import Link from 'next/link';
import './globals.css';
import Header from './Header';
import Footer from './Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className='mx-auto max-w-2xl px-4'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
