/* eslint-disable react/no-unescaped-entities */
import Link from 'next/link';
import './globals.css';
import Header from './Header';
import Footer from './Footer';
import { Montserrat } from 'next/font/google';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={montserrat.variable}>
      <body className='bg-slate-800 min-h-screen max-w-xs md:max-w-2xl mx-auto flex flex-col'>
        <div className='flex flex-col flex-1  justify-center '>
          {children}
        </div>

        <div className=''>
          <Footer />
        </div>
      </body>
    </html>
  );
}
