/* eslint-disable react/no-unescaped-entities */
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <h1 className='text-3xl'>Wassem's Blog</h1>
      <p>Welcome to my tech blog</p>
      <br />
    </header>
  );

  const footer = (
    <footer>
      <br />
      <p>Developed by Wassem</p>
    </footer>
  );
  return (
    <html lang='en'>
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
